#pragma once

enum ChordType{
//    major(rest: Partial<IBuildChordTypeParam>){ return c({ type: 'Major', pattern: [1, 3, 5], ...rest }); },
//    minor(rest: Partial<IBuildChordTypeParam>){ return c({ type: 'Minor', pattern: [1, _3b, 5], ...rest }); },
//    major7th(rest: Partial<IBuildChordTypeParam>){ return c({ type: 'Major 7th', pattern: [1, 3, 5, 7], ...rest }); },
//    minor7th(rest: Partial<IBuildChordTypeParam>){ return c({ type: 'Minor 7th',  pattern: [1, _3b, 5, _7b], ...rest }); },
//    minorMajor7th(rest: Partial<IBuildChordTypeParam>){ return c({ type: 'Minor Major 7th',  pattern: [1, _3b, 5, 7], ...rest }); },
//    sustained4(rest: Partial<IBuildChordTypeParam>){ return c({ type: 'Sustained 4',  pattern: [1, 4, 5], ...rest }); },
//    sustained2(rest: Partial<IBuildChordTypeParam>){ return c({ type: 'Sustained 2',  pattern: [1, 2, 5], ...rest }); },
//    _6(rest: Partial<IBuildChordTypeParam>){ return c({ type: '6',  pattern: [1, 3, 5, 6], ...rest }); },
//    minor6(rest: Partial<IBuildChordTypeParam>){ return c({ type: 'Minor 6',  pattern: [1, _3b, 5, 6], ...rest }); },
//    _9(rest: Partial<IBuildChordTypeParam>){ return c({ type: '9',  pattern: [1, 3, 5, _7b, 9], ...rest }); },
//    minor9(rest: Partial<IBuildChordTypeParam>){ return c({ type: 'Minor 9',  pattern: [1, _3b, 5, _7b, 9], ...rest }); },
//    major9(rest: Partial<IBuildChordTypeParam>){ return c({ type: 'Major 9',  pattern: [1, 3, 5, 7, 9], ...rest }); },
//    minorMajor9(rest: Partial<IBuildChordTypeParam>){ return c({ type: 'Minor Major 9',  pattern: [1, _3b, 5, 7, 9], ...rest }); },
//    _11(rest: Partial<IBuildChordTypeParam>){ return c({ type: '11',  pattern: [1, 3, 5, _7b, 9, 11], ...rest }); },
//    minor11(rest: Partial<IBuildChordTypeParam>){ return c({ type: 'Minor 11',  pattern: [1, _3b, 5, _7b, 9, 11], ...rest }); },
//    major11(rest: Partial<IBuildChordTypeParam>){ return c({ type: 'Major 11',  pattern: [1, 3, 5, 7, 9, 11], ...rest }); },
//    minorMajor11(rest: Partial<IBuildChordTypeParam>){ return c({ type: 'Minor Major 11',  pattern: [1, _3b, 5, 7, 9, 11], ...rest }); },
//    _13(rest: Partial<IBuildChordTypeParam>){ return c({ type: '13',  pattern: [1, 3, 5, _7b, 9, 13], ...rest }); },
//    minor13(rest: Partial<IBuildChordTypeParam>){ return c({ type: 'Minor 13',  pattern: [1, _3b, 5, _7b, 9, 13], ...rest }); },
//    major13(rest: Partial<IBuildChordTypeParam>){ return c({ type: 'Major 13',  pattern: [1, 3, 5, 7, 9, 13], ...rest }); },
//    minorMajor13(rest: Partial<IBuildChordTypeParam>){ return c({ type: 'Minor Major 13',  pattern: [1, _3b, 5, 7, 9, 13], ...rest }); },
//    add9(rest: Partial<IBuildChordTypeParam>){ return c({ type: 'Add 9',  pattern: [1, 3, 5, 9], ...rest }); },
//    minorAdd9(rest: Partial<IBuildChordTypeParam>){ return c({ type: 'Minor Add 9',  pattern: [1, _3b, 5, 9], ...rest }); },
//    _6add9(rest: Partial<IBuildChordTypeParam>){ return c({ type: '6 Add 9',  pattern: [1, 3, 5, 6, 9], ...rest }); },
//    minor6add9(rest: Partial<IBuildChordTypeParam>){ return c({ type: 'Minor 6 Add 9',  pattern: [1, _3b, 5, 6, 9], ...rest }); },
//    dominant7thAdd11(rest: Partial<IBuildChordTypeParam>){ return c({ type: 'Dominant 7th Add 11',  pattern: [1, 3, 5, _7b, 11], ...rest }); },
//    major7thAdd11(rest: Partial<IBuildChordTypeParam>){ return c({ type: 'Major 7th Add 11',  pattern: [1, 3, 5, 7, 11], ...rest }); },
//    minor7thAdd11(rest: Partial<IBuildChordTypeParam>){ return c({ type: 'Minor 7th Add 11',  pattern: [1, _3b, 5, _7b, 11], ...rest }); },
//    minorMajor7thAdd11(rest: Partial<IBuildChordTypeParam>){ return c({ type: 'Minor Major 7th Add 11',  pattern: [1, _3b, 5, 7, 11], ...rest }); },
//    dominant7thAdd13(rest: Partial<IBuildChordTypeParam>){ return c({ type: 'Dominant 7th Add 13',  pattern: [1, 3, 5, _7b, 13], ...rest }); },
//    major7thAdd13(rest: Partial<IBuildChordTypeParam>){ return c({ type: 'Major 7th Add 13',  pattern: [1, 3, 5, 7, 13], ...rest }); },
//    minor7thAdd13,
//    minorMajor7thAdd13,
//    _7flat5,
//    _7sharp5,
//    _7flat9,
//    _7sharp9,
//    _7sharp5flat9,
//    minorflat5,
//    minor7flat5,
//    minor7sharp5,
//    minor7flat9,
//    _9sharp11,
//    _9flat13,
//    _6sustained4,
//    _7sustained4,
//    major7thsustained4,
//    _9sustained4,
//    major9thsustained4,
//    root,
//    dyad1and5,
//    dyad1and3,
};